version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build artifact
          command: go build
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            go test -race -coverprofile=coverage.txt -covermode=atomic ./functions/docker/
      - run:
          name: Upload coverage report to codecov
          command: |
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: /tmp/test-reports
